[build]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "always"

[env]
PORT = "8000"
